import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const app = express();
const PORT = 3000;

app.use(express.json());

// Initialize Gemini client lazily to avoid immediate startup crashes
let ai: GoogleGenAI | null = null;
function getGeminiClient() {
  if (!ai) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      console.warn("Warning: GEMINI_API_KEY environment variable is not defined.");
    }
    ai = new GoogleGenAI({
      apiKey: apiKey || "",
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build",
        },
      },
    });
  }
  return ai;
}

// Secure Gemini chat endpoint proxy
app.post("/api/chat", async (req, res) => {
  try {
    const { messages, systemInstruction, temperature, maxTokens } = req.body;

    if (!process.env.GEMINI_API_KEY) {
      return res.status(400).json({
        error: "GEMINI_API_KEY is not defined on the server secrets. Please add it or use LM Studio mode instead.",
      });
    }

    if (!messages || !Array.isArray(messages) || messages.length === 0) {
      return res.status(400).json({ error: "Invalid or empty messages history." });
    }

    const client = getGeminiClient();

    // Map conversation array to Google GenAI contents schema
    const contents = messages.map((m: any) => ({
      role: m.role === "assistant" ? "model" : "user",
      parts: [{ text: m.content }],
    }));

    const response = await client.models.generateContent({
      model: "gemini-3.5-flash",
      contents,
      config: {
        systemInstruction: systemInstruction || "You are a helpful, professional assistant answering of elegant prose.",
        temperature: temperature !== undefined ? Number(temperature) : 0.7,
        ...(maxTokens ? { maxOutputTokens: Number(maxTokens) } : {}),
      },
    });

    res.json({
      role: "assistant",
      content: response.text || "No response generated by the model.",
    });
  } catch (error: any) {
    console.error("Gemini API Error in proxy server:", error);
    res.status(500).json({
      error: error?.message || "An error occurred during message generation with Gemini.",
    });
  }
});

// Entrypoint to build/run Vite dev or production server
async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server is running on port ${PORT}`);
  });
}

startServer();
